### ISSUE TITLE
Support Serialize/Deserialize

### ISSUE THREAD

**Issue by ISibboI** [tov/succinct-rs#2]
It would be awesome if this would support serde's Serialize and Deserialize.

**Comment by tov** [comment]
I don’t think that would be too difficult, but I'm wondering which types you want it for.

I've extracted the bitvector data structure into [another crate](https://crates.io/crates/bv), and the version there is better at this point. It supports serde serialization/deserialization already, if you enable the `serde` feature in Cargo. I'm planning to make the `succinct` crate depend on the `bv` crate at some point rather than defining its own bitvectors, and at that point I will probably make the other types in `succinct` support serde as well. (I don't think I'll have time to do it this month, though.)

**Comment by ISibboI** [comment]
Thank you for the hint, I did not know about that. Then I will use this crate.
